---
# ansible-playbook /home/botz/Documents/Practice/Ansible/Playbooks-remote/shelly-store.com/front/new-repo.yml
- name: shelly-store.com pull
  hosts: shellyStore
  tasks:

    - name: tellme who you are 1
      shell:
        cmd: git config --global user.email "mlmjm123@gmail.com"
    
    - name: tellme who you are 2
      shell:
        cmd: git config --global user.name "Ansible root"

    
    - name: remove old repo
      shell:
        cmd: cd /home/botz/; rm -r /home/botz/shelly2-front-production

    - name: create repo folder
      shell:
        cmd: cd /home/botz/; mkdir shelly2-front-production

    - name: git init
      shell:
        cmd: cd /home/botz/shelly2-front-production; git init
    
    - name: add remote origin shelly-store.com
      shell:
        cmd: cd /home/botz/shelly2-front-production; git remote add origin https://github.com/StevenBarquet/shelly2-front-production.git
...