---
# ansible-playbook /home/botz/Documents/Practice/Ansible/Playbooks-remote/update-front-all.yml
- name: Update remote repos
  hosts: shellyStore
  tasks:

# Update prod apps in servers
- name: Run playbook shelly-store.com main-front
  import_playbook: shelly-store.com/main-front.yml

- name: Run playbook copiadorasqueen.com main-front
  import_playbook: copiadorasqueen.com/main-front.yml

...