---
# ansible-playbook /home/botz/Documents/Practice/Ansible/Playbooks-local/shelly-store.com/pullMaster.yml
- name: shelly-store.com docker stuff
  hosts: shellyStore
  tasks:
    
    - name: remove container
      shell:
        cmd: docker container rm -f shelly-back-container
    
    - name: remove image
      shell:
        cmd: docker image rm -f shelly_back_image

    - name: build new backend image shelly-store.com
      shell:
        cmd: cd /home/botz/shelly-back2; docker build -t shelly_back_image .
    
    - name: mount new container
      shell:
        cmd: docker run --network host --name shelly-back-container --env DOMAIN=shelly-store.com --env SSL_PATH=/etc/letsencrypt/live/shelly-store.com -p 4000:4000 -d --restart unless-stopped --mount type=bind,source=/etc/letsencrypt/live/shelly-store.com,target=/etc/letsencrypt/live/shelly-store.com --mount type=bind,source=/etc/letsencrypt/archive/shelly-store.com,target=/etc/letsencrypt/archive/shelly-store.com shelly_back_image
...