---
# ansible-playbook /home/botz/Documents/Practice/Ansible/Playbooks-local/master-app-update-all.yml
- name: update shelly-store.com repos
  hosts: local
  tasks:

# Prepare main app before update repos
- name: Run playbook commitMaster
  import_playbook: master-branch.com/Client/commitMaster.yml

- name: Run playbook backupFiles
  import_playbook: master-branch.com/Client/backupFiles.yml

# Update prod repos
- name: Run playbook shelly-store.com masterUpdate
  import_playbook: shelly-store.com/clientUpdate.yml

- name: Run playbook copiadorasqueen.com masterUpdate
  import_playbook: copiadorasqueen.com/clientUpdate.yml

# Restore repos to continue develop
- name: Run playbook restartplays
  import_playbook: master-branch.com/Client/restartplays.yml
...