---
# ansible-playbook /home/botz/Documents/Practice/Ansible/Playbooks-local/shelly-store.com/restoreJSON.yml
- name: shelly-store.com restore files
  hosts: local
  tasks:

    - name: Restore store-data.json shelly-store.com
      ansible.builtin.copy:
        src: /home/botz/Documents/Practice/Ansible/Playbooks-local/shelly-store.com/Client/Backup/store-data.json
        dest: /home/botz/Documents/A_Programing/Shelly4-Client-App/src/javascript/others/store-data.json
        owner: botz
        group: botz
        mode: '0644'
    
    - name: restore logo shelly-store.com
      ansible.builtin.copy:
        src: /home/botz/Documents/Practice/Ansible/Playbooks-local/shelly-store.com/Client/Backup/images/logoStoreL.png
        dest: /home/botz/Documents/A_Programing/Shelly4-Client-App/src/images/logoStoreL.png
        owner: botz
        group: botz
        mode: '0644'
    
    - name: Restore privilages
      shell:
        cmd: chmod ugo+wrx /home/botz/Documents/A_Programing/Shelly4-Client-App -Rf
...